var res = {
    //backgrounds
    bg_open_jpg : "res/bg_open.jpg",
    bg_menu_1_png : "res/menu_1.png",
    bg_barn_png : "res/bg_barn.png",
    bg_market_png : "res/bg_market.png",
    bg_status_png : "res/bg_status.png",
    bg_title_png : "res/bg_title.png",
    bg_dialog_png : "res/bg_dialog.png",
    bg_single_good_png : "res/bg_single_good.png",
    
    //buttons
    btn_exit_unclicked_png : "res/btn_exit_unclicked.png",
    btn_exit_clicked_png : "res/btn_exit_clicked.png",
    btn_barn_unclicked_png : "res/barn_unclicked.png",
    btn_barn_clicked_png : "res/barn_clicked.png",
    btn_market_unclicked_png : "res/market_unclicked.png",
    btn_market_clicked_png : "res/market_clicked.png",
    btn_next_city_unclicked_png : "res/next_city_unclicked.png",
    btn_next_city_clicked_png : "res/next_city_clicked.png",
    btn_buy_unclicked_png : "res/btn_buy_unclicked.png",
    btn_buy_clicked_png : "res/btn_buy_clicked.png",
    btn_sell_unclicked_png : "res/btn_sell_unclicked.png",
    btn_sell_clicked_png : "res/btn_sell_clicked.png",
    btn_plus_png : "res/btn_plus.png",
    btn_minus_png : "res/btn_minus.png",
    btn_plus_minus_disabled_png : "res/btn_plus_minus_disabled.png",

    //goods
    good_bread_png: "res/good_bread.png",
    good_candle_png: "res/good_candle.png",
    good_book_png: "res/good_book.png",
    good_painting_png: "res/good_painting.png",
    good_woods_png: "res/good_woods.png",
    good_mystery_water_png: "res/good_mystery_water.png",

    //for fight scene
    bg_fight_png : "res/ball_background.png",
    red_ball_png : "res/red_ball.png",
    blue_ball_png : "res/blue_ball.png",
    green_ball_png : "res/green_ball.png",
    gold_ball_png : "res/gold_ball.png",
    silver_ball_png : "res/silver_ball.png",
    peach_ball_png : "res/peach_ball.png",
    null_ball_png : "res/null_ball.png",

    monster_slime_png : "res/monster_slime.png",
    monster_sagma_png : "res/monster_sagma.png",
    monster_ghast_png : "res/monster_ghast.png",
    monster_silverfish_png : "res/monster_silverfish.png",
    monster_creeper_png : "res/monster_silverfish.png",
    monster_zombie_png : "res/monster_zombie.png",
    monster_witch_png : "res/monster_witch.png",
    monster_blaze_png : "res/monster_blaze.png",
    monster_skeleton_png : "res/monster_skeleton.png",
    monster_cat_png : "res/monster_cat.png",


    combo_1_png : "res/1_combo.png",
    combo_2_png : "res/2_combo.png",
    combo_3_png : "res/3_combo.png",
    combo_4_png : "res/4_combo.png",
    combo_5_png : "res/5_combo.png",
    combo_6_png : "res/6_combo.png",
    combo_7_png : "res/7_combo.png",
    combo_8_png : "res/8_combo.png",
    combo_9_png : "res/9_combo.png",
    combo_10_png : "res/10_combo.png",
    combo_11_png : "res/11_combo.png",
    combo_12_png : "res/12_combo.png",
    combo_13_png : "res/13_combo.png",
    combo_14_png : "res/14_combo.png",
    combo_15_png : "res/15_combo.png",
    combo_16_png : "res/16_combo.png",
    combo_17_png : "res/17_combo.png",
    combo_18_png : "res/18_combo.png",
    combo_19_png : "res/19_combo.png",
    combo_20_png : "res/20_combo.png",
    combo_21_png : "res/21_combo.png",
    combo_22_png : "res/22_combo.png",
    combo_23_png : "res/23_combo.png",
    combo_24_png : "res/24_combo.png",
    combo_25_png : "res/25_combo.png",
    combo_26_png : "res/26_combo.png",
    combo_27_png : "res/27_combo.png",
    combo_28_png : "res/28_combo.png",
    combo_29_png : "res/29_combo.png",
    combo_30_png : "res/30_combo.png",

    //other
    player_png : "res/runner.png",
    city_1_tmx : "res/city_1.tmx",
    xxx : "res/Environment-3.png",
    change_day_mask_png : "res/change_day_mask.png"
};

var g_resources = [
    //image
    res.bg_open_jpg,
    res.bg_barn_png,
    res.bg_market_png,
    res.bg_status_png,
    res.bg_title_png,
    res.bg_dialog_png,
    res.bg_single_good_png,
    res.player_png,
    res.bg_menu_1_png,
    res.bg_fight_png,
    res.xxx,
    //buttons
    res.btn_exit_unclicked_png,
    res.btn_exit_clicked_png,
    res.btn_barn_unclicked_png,
    res.btn_barn_clicked_png,
    res.btn_market_unclicked_png,
    res.btn_market_clicked_png,
    res.btn_next_city_unclicked_png,
    res.btn_next_city_clicked_png,
    res.btn_buy_unclicked_png,
    res.btn_buy_clicked_png,
    res.btn_sell_unclicked_png,
    res.btn_sell_clicked_png,
    res.btn_plus_png,
    res.btn_minus_png,
    res.btn_plus_minus_disabled_png,
    //goods
    res.good_bread_png,
    res.good_candle_png,
    res.good_book_png,
    res.good_painting_png,
    res.good_woods_png,
    res.good_mystery_water_png,

    //balls
    res.red_ball_png,
    res.blue_ball_png,
    res.green_ball_png,
    res.gold_ball_png,
    res.silver_ball_png,
    res.peach_ball_png,
    res.null_ball_png,

    //monsters
    res.monster_slime_png,
    res.monster_sagma_png,
    res.monster_ghast_png,
    res.monster_silverfish_png,
    res.monster_creeper_png,
    res.monster_zombie_png,
    res.monster_witch_png,
    res.monster_blaze_png,
    res.monster_skeleton_png,
    res.monster_cat_png,

    //combos
    res.combo_1_png,
    res.combo_2_png,
    res.combo_3_png,
    res.combo_4_png,
    res.combo_5_png,
    res.combo_6_png,
    res.combo_7_png,
    res.combo_8_png,
    res.combo_9_png,
    res.combo_10_png,
    res.combo_11_png,
    res.combo_12_png,
    res.combo_13_png,
    res.combo_14_png,
    res.combo_15_png,
    res.combo_16_png,
    res.combo_17_png,
    res.combo_18_png,
    res.combo_19_png,
    res.combo_20_png,
    res.combo_21_png,
    res.combo_22_png,
    res.combo_23_png,
    res.combo_24_png,
    res.combo_25_png,
    res.combo_26_png,
    res.combo_27_png,
    res.combo_28_png,
    res.combo_29_png,
    res.combo_30_png,

    //plist

    //fnt

    //tmx
    res.city_1_tmx,
    //bgm

    //effect
    res.change_day_mask_png
];